site_name: Symnix - User Documentation
site_url: https://symnixhq.github.io/portal/
nav:
  - Overview: index.md
  - getting_started.md
  - faq.md
  - Support: support.md
theme:
  name: material
  font: Work Sans
